#!/bin/bash

deepspeed llava/train/train_mem.py \
    --deepspeed ./scripts/zero3.json \
    --model_name_or_path /home/yhlin/models/llava-v1.5-7b \
    --version v1 \
    --data_path /home/yhlin/LLaVA/playground/warehouse_sft.json \
    --image_folder /home/yhlin/LLaVA/playground/warehouse_data/ \
    --vision_tower /home/yhlin/models/DFN5B-CLIP-ViT-H-14-378 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir /home/yhlin/models/llava-v1.5-7b-task \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4p \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 500 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 1\
    --lazy_preprocess True \
    --report_to wandb
